version: '3.8'

services:
  booking:
    image: yunglordyaya/taxa-service:latest
    environment:
      - DocPath=../srv/docs/
      - RabbitMQ=dev-rabbit
    ports:
      - "5001:80"
    networks:
      - default
    volumes:
      - docs:/srv/docs
  planning:
    image: stevethebeef7/planning-service-image:latest
    environment:
      - DocPath=../srv/docs/
      - RabbitMQ=dev-rabbit
    ports:
      - "5002:80"
    networks:
      - default
    volumes:
      - docs:/srv/docs
    depends_on:
      - rabbitmq

volumes:
 images:
  external: false
networks:
 default:
  driver: bridge
  name: mitnet